#!/usr/bin/env python3

import re

with open("/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq") as f:
    cpuinfo = f.read()

if not cpuinfo:
    raise RuntimeError("Could not determine CPU frequency")

score = float(cpuinfo) / 1000

iterations = int(score / 6)

print(f"*FvwmAnimate: Iterations {iterations}")
